[colors.primary]
background = '#ffffff'
foreground = '#2a2b33'

[colors.normal]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#bbbbbb'

[colors.bright]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#ffffff'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#a40e26'

