import = ["~/.config/alacritty/themes/active.toml"]

# [colors.primary]
# background = "0x1a202a"

[font]
size = 9.5

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[shell]
program = "/home/kotur/.nix-profile/bin/zsh"

[env]
WINIT_X11_SCALE_FACTOR = "1"
ALACRITTY = "true"
