"""Durable per-session scopes for claude-multi.

A scope is the per-session directory ``<state_root>/scopes/<uuid>/`` holding
every generated, policy-relevant file for one managed session::

    scopes/<uuid>/
    ├── .claude/agents/<variant-id>.md   # one per selected variant
    └── settings.json                    # compiled session settings

``compile_scope`` is pure: it maps (resolved composition, trusted catalog
roles and prompt bodies, catalog metadata) to a plan of file bytes plus the
compiled settings document. ``write_scope`` is the only effect: it stages the
plan into the sibling ``scopes/.<uuid>.new/`` with per-file
``state.atomic_write``, then renames the staging directory into
``scopes/<uuid>/`` and fsyncs the ``scopes/`` parent, so a crash never
leaves a half-written live scope. Scope content is a pure function of
(record composition, installed catalog); a lost or drifted scope is always
re-derivable from those two authorities.

The exact-``cm-*`` collision gate (:func:`find_cm_collisions`) scans project
agent directories, passthrough ``--add-dir`` agent directories, and the
managed settings agents directory for agent files whose frontmatter ``name``
exactly equals one of the session's generated variant IDs. A collision would
silently shadow a guaranteed definition (closest-to-cwd precedence), so the
launcher fails closed naming the offending file. The scanner is line-wise:
no YAML dependency, tolerant of unreadable files (a file the session user
cannot read cannot shadow anything either).
"""

from __future__ import annotations

import errno
import os
import shlex
import shutil
import stat
import uuid
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

from . import compiler, state, strict_json
from .composition import ResolvedComposition


class ScopeError(ValueError):
    """Raised when a scope cannot be compiled or written (fail closed)."""


# SPEC 2.1 durable floor, verbatim. Every generated description carries the
# no-substitution sentinel so the rule survives lead-appendix loss (U2).
SENTINEL_SUFFIX = (
    "Managed cm session: if a selected cm-* type is unavailable, stop; "
    "never substitute a generic agent."
)

# SPEC 2.1 cross-family independence rule, verbatim template; carried by
# cm-reviewer variant descriptions only.
REVIEW_INDEPENDENCE = (
    "Review independence: a change authored by a {family}-family variant "
    "must not receive its sole verdict from another {family}-family variant "
    "while a cross-family reviewer is enabled."
)

# Closed compiled-settings key allowlist (SPEC 2.2). Nothing else is emitted.
COMPILED_SETTINGS_KEYS = frozenset(
    {
        "disableWorkflows",
        "workflowSizeGuideline",
        "workflowKeywordTriggerEnabled",
        "permissions",
        "availableModels",
        "model",
        "worktree",
        "env",
        "hooks",
        "autoCompactEnabled",
        "apiKeyHelper",
    }
)

# The three workflow keys the package base settings.json must supply.
_BASE_WORKFLOW_KEYS = ("disableWorkflows", "workflowSizeGuideline", "workflowKeywordTriggerEnabled")

DEFAULT_MANAGED_AGENTS_DIR = Path("/etc/claude-code/.claude/agents")

_AGENT_DIR_RELPATH = PurePosixPath(".claude/agents")

# Stable lifecycle-hook indirection: compiled scopes embed THIS constant path
# (per state root), never a package/store path, so scope bytes survive package
# rebuilds unchanged. The shim is regenerated by the launcher and execs the
# currently resolved claude-multi, falling back to PATH lookup.
HOOK_SHIM_RELATIVE = PurePosixPath("bin/claude-multi-hook")
GATEWAY_TOKEN_SHIM_RELATIVE = PurePosixPath("bin/claude-multi-gateway-token")


def hook_shim_path(state_root: Path | str) -> Path:
    """The stable lifecycle-hook command path embedded in compiled scopes."""

    return Path(state_root) / HOOK_SHIM_RELATIVE


def gateway_token_shim_path(state_root: Path | str) -> Path:
    """The stable apiKeyHelper path embedded in compiled scopes."""

    return Path(state_root) / GATEWAY_TOKEN_SHIM_RELATIVE


def resolve_gateway_token_path(environ: dict[str, str] | None = None) -> Path:
    """Where the loopback gateway token lives (never embedded in scopes).

    Strictly HOME-relative, matching the token's two authorities: the writer
    (``proxy.config_dir``) and the reader (launch resolves the catalog-pinned
    ``gateway.token_file`` against HOME). It deliberately does NOT follow
    ``XDG_CONFIG_HOME`` — compositions and the contract override do (via
    ``sessions.config_root``), but the token location is catalog-pinned, so
    an XDG-aware shim would point at a file the system never populates
    (hardening review H1).
    """

    env = os.environ if environ is None else environ
    return Path(env.get("HOME", str(Path.home()))) / ".config" / "claude-multi" / "api-key"


def ensure_gateway_token_shim(state_root: Path | str, token_path: Path | str) -> Path:
    """Write/refresh the apiKeyHelper shim; return the path to embed in scopes.

    Same discipline as the hook shim: idempotent crash-safe write, mode
    repaired unconditionally. The shim prints the gateway token at runtime
    (the token itself never enters scope files), so sessions relaunched by
    the background daemon — which scrubs ANTHROPIC_* from its children's
    environment — keep their gateway routing through the compiled settings
    ``apiKeyHelper`` + ``env.ANTHROPIC_BASE_URL``.
    """

    token_path = Path(token_path)
    quoted = shlex.quote(str(token_path))
    content = (
        "#!/bin/sh\n"
        "# claude-multi gateway token helper (Claude Code apiKeyHelper) - stable\n"
        "# path embedded in compiled scopes. Regenerated by the launcher; do\n"
        "# not edit. Prints the loopback gateway token from its owner-only file\n"
        "# so daemon-relaunched sessions (whose ANTHROPIC_* env is scrubbed by\n"
        "# the daemon) still authenticate to the gateway.\n"
        f"exec cat {quoted}\n"
    ).encode("utf-8")
    path = gateway_token_shim_path(state_root)
    state.ensure_private_dir(path.parent)
    try:
        current = state.read_private(path)
    except state.StateError:
        current = None
    if current != content:
        state.atomic_write(path, content)
    if stat.S_IMODE(os.lstat(path).st_mode) != 0o700:
        os.chmod(path, 0o700)
    return path


def ensure_token_helper_command(
    state_root: Path | str, environ: dict[str, str] | None = None
) -> str:
    """One-call resolver: ensure the token shim, return the command to embed."""

    return str(
        ensure_gateway_token_shim(state_root, resolve_gateway_token_path(environ))
    )


def resolve_hook_command(
    environ: dict[str, str] | None = None, asset_root: Path | str | None = None
) -> str:
    """The single authority for the real claude-multi command the shim execs.

    Every caller — launcher, transition engine, repair, cleanup — must derive
    the hook command here so all scopes share one spelling. Precedence:
    ``CLAUDE_MULTI_HOOK_COMMAND`` (set by the installed wrapper), then
    ``<asset_root>/bin/claude-multi`` resolved.
    """

    env = os.environ if environ is None else environ
    configured = env.get("CLAUDE_MULTI_HOOK_COMMAND")
    if configured:
        return str(Path(configured).resolve())
    if asset_root is None:
        raise ScopeError(
            "no hook command available: CLAUDE_MULTI_HOOK_COMMAND is unset "
            "and no asset root was supplied"
        )
    return str((Path(asset_root) / "bin" / "claude-multi").resolve())


def ensure_hook_shim(state_root: Path | str, resolved_command: str) -> Path:
    """Write/refresh the stable hook shim; return the path to embed in scopes.

    Idempotent and crash-safe (``state.atomic_write``); only rewrites when the
    content changed. The shim prefers the resolved command (refreshed by every
    launcher invocation, so it tracks the newest installed package) and falls
    back to a PATH lookup, so hooks keep working if the exact package path was
    garbage-collected but claude-multi remains installed.
    """

    if not resolved_command:
        raise ScopeError("cannot write the hook shim without a resolved command")
    quoted = shlex.quote(resolved_command)
    content = (
        "#!/bin/sh\n"
        "# claude-multi lifecycle hook shim - stable path embedded in compiled\n"
        "# scopes. Regenerated by the launcher; do not edit. Prefers the\n"
        "# resolved launcher command so hooks track the newest install; falls\n"
        "# back to PATH so a garbage-collected package path cannot strand them.\n"
        f"if [ -x {quoted} ]; then\n"
        f"    exec {quoted} \"$@\"\n"
        "fi\n"
        "if command -v claude-multi >/dev/null 2>&1; then\n"
        "    exec claude-multi \"$@\"\n"
        "fi\n"
        "echo 'claude-multi hook shim: no claude-multi launcher found' >&2\n"
        "exit 1\n"
    ).encode("utf-8")
    path = hook_shim_path(state_root)
    state.ensure_private_dir(path.parent)
    try:
        current = state.read_private(path)
    except state.StateError:
        current = None
    if current != content:
        state.atomic_write(path, content)
    # Repair the mode unconditionally: a crash between the atomic write and
    # the chmod must never leave a permanently non-executable shim (content
    # matches, so the write above would be skipped and hooks would EACCES).
    if stat.S_IMODE(os.lstat(path).st_mode) != 0o700:
        os.chmod(path, 0o700)
    return path


def _check_session_id(session_id: str) -> str:
    """Require the canonical lowercase UUIDv4 used by scope path names."""

    try:
        parsed = uuid.UUID(session_id)
    except (AttributeError, TypeError, ValueError) as exc:
        raise ScopeError(f"session id {session_id!r} is not a UUIDv4") from exc
    if parsed.version != 4 or str(parsed) != session_id:
        raise ScopeError(f"session id {session_id!r} is not a UUIDv4")
    return session_id


@dataclass(frozen=True)
class CatalogMeta:
    """Catalog-derived metadata the scope compiler needs beyond the resolution.

    ``base_settings`` is the package base ``settings.json`` document (merge
    base); ``client_selectors`` is every client selector the trusted catalog
    declares (model-level and per-lane); ``generic_agent_aliases`` is the
    native-contract's recorded generic agent aliases.
    """

    base_settings: dict[str, Any]
    client_selectors: tuple[str, ...]
    generic_agent_aliases: tuple[str, ...]
    gateway_base_url: str


@dataclass(frozen=True)
class ScopePlan:
    """Pure scope content: file bytes by scope-relative path, plus settings."""

    agent_files: dict[str, bytes]
    settings: dict[str, Any]

    @property
    def agent_names(self) -> frozenset[str]:
        """Generated variant IDs (the ``cm-*`` names the collision gate owns)."""

        return frozenset(PurePosixPath(relpath).stem for relpath in self.agent_files)


def catalog_meta_from_docs(docs: dict[str, Any]) -> CatalogMeta:
    """Build :class:`CatalogMeta` from the loaded trusted catalog documents."""

    selectors: set[str] = set()
    for model in docs["models"]["models"].values():
        selectors.add(model["client_selector"])
        for lane in model["lanes"].values():
            selectors.add(lane["client_selector"])
    return CatalogMeta(
        base_settings=dict(docs["settings"]),
        client_selectors=tuple(sorted(selectors)),
        generic_agent_aliases=tuple(
            docs["native-contract"]["generic_agent_aliases"]["values"]
        ),
        gateway_base_url=docs["gateway"]["gateway"]["base_url"],
    )


def _yaml_double_quoted(value: str) -> str:
    """YAML double-quoted scalar: safe for descriptions containing ': '."""

    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _agent_file_bytes(
    resolved: ResolvedComposition,
    roles: dict[str, Any],
    prompt_bodies: dict[str, bytes],
    variant: Any,
) -> bytes:
    role = roles[variant.role]
    if role.get("tools") or role.get("disallowed_tools"):
        raise ScopeError(
            f"role {variant.role!r} declares frontmatter tools/disallowed_tools; "
            "emitting them is not implemented (fail closed)"
        )
    if variant.agent_effort == "ultracode":
        raise ScopeError(
            f"variant {variant.id!r}: ultracode is a lead-only effort and must "
            "never appear as an agent effort value"
        )
    description = compiler.variant_description(
        role, {"display": variant.display}, variant
    )
    description = f"{description} {SENTINEL_SUFFIX}"
    if variant.role == "cm-reviewer":
        description = (
            f"{description} {REVIEW_INDEPENDENCE.format(family=variant.family)}"
        )
    lines = [
        "---",
        f"name: {variant.id}",
        f"description: {_yaml_double_quoted(description)}",
        f"model: {variant.client_selector}",
        f"effort: {variant.agent_effort}",
    ]
    if variant.isolation is not None:
        lines.append(f"isolation: {variant.isolation}")
    lines.append("---")
    lines.append("")
    header = "\n".join(lines) + "\n"
    return header.encode("utf-8") + prompt_bodies[variant.role]


def _lifecycle_settings(
    managed_id: str,
    hook_command: str,
    launch_epoch: int = 0,
    *,
    gateway_base_url: str | None = None,
    token_helper_command: str | None = None,
    retry_watchdog: bool = False,
) -> dict[str, Any]:
    """Compiled metadata-only lifecycle hook settings for one stable scope.

    ``gateway_base_url``/``token_helper_command`` make gateway routing itself
    durable: the base URL is non-secret and the helper prints the token at
    runtime, so sessions relaunched by the background daemon (which scrubs
    ANTHROPIC_* env from its children) keep working instead of failing with
    "invalid model".
    """

    _check_session_id(managed_id)
    if not hook_command:
        raise ScopeError("lifecycle hook command is empty")
    if not isinstance(launch_epoch, int) or isinstance(launch_epoch, bool) or launch_epoch < 0:
        raise ScopeError("lifecycle launch_epoch must be a non-negative integer")
    quoted = shlex.quote(hook_command)
    stable = shlex.quote(managed_id)

    def command(event: str) -> dict[str, Any]:
        return {
            "type": "command",
            "command": (
                f"{quoted} session-event {event} --managed-id {stable} "
                f"--launch-epoch {launch_epoch}"
            ),
            "timeout": 5,
        }

    env = {
        "CLAUDE_MULTI_MANAGED_ID": managed_id,
        "CLAUDE_MULTI_LAUNCH_EPOCH": str(launch_epoch),
        # Compatibility for scopes created before the identity split.
        "CLAUDE_MULTI_SESSION_ID": managed_id,
    }
    if retry_watchdog:
        # Managed sessions own their recovery policy (issue 004, doctrine
        # #8): watchdog mode raises the transient-retry budget so a
        # subagent or a backgrounded turn never dies waiting for a human
        # to type "continue" (binary-verified at 2.1.220: 300 retries, no
        # 60s retry-after abort). Ordinary sessions stay unpinned by
        # design; mid-stream-after-content errors stay unrecoverable.
        env["CLAUDE_CODE_RETRY_WATCHDOG"] = "1"
    if gateway_base_url:
        env["ANTHROPIC_BASE_URL"] = gateway_base_url
    settings: dict[str, Any] = {
        "env": env,
        "hooks": {
            "SessionStart": [{"hooks": [command("start")]}],
            "SessionEnd": [{"hooks": [command("end")]}],
        },
    }
    if token_helper_command:
        settings["apiKeyHelper"] = token_helper_command
    return settings


def compile_scope(
    resolved: ResolvedComposition,
    roles: dict[str, Any],
    prompt_bodies: dict[str, bytes],
    catalog_meta: CatalogMeta,
    *,
    managed_id: str | None = None,
    hook_command: str | None = None,
    launch_epoch: int = 0,
    token_helper_command: str | None = None,
) -> ScopePlan:
    """Pure per-session scope plan. No effects; fail closed on policy gaps."""

    agent_files: dict[str, bytes] = {}
    for variant in resolved.variants:
        relpath = str(_AGENT_DIR_RELPATH / f"{variant.id}.md")
        agent_files[relpath] = _agent_file_bytes(
            resolved, roles, prompt_bodies, variant
        )

    _, denies = compiler.compile_native_policy(
        resolved.native_agents, catalog_meta.generic_agent_aliases
    )
    settings = dict(catalog_meta.base_settings)
    settings["disableWorkflows"] = resolved.workflows == "off"
    settings["permissions"] = {"deny": denies}
    # A managed composition owns the lead. Exposing the whole catalog here lets
    # native /model change only the main thread while leaving the recorded
    # composition and generated roster stale. Composition transitions are the
    # only supported cross-model change.
    # availableModels governs TWO things in Claude Code: the /model menu
    # AND agent frontmatter model resolution. A lead-only fence silently
    # degrades every variant's dispatch to the lead model (the subagent
    # named Sol runs on the lead instead — verified live: Sol-typed agents
    # issued claude-multi-kimi-k3 requests, and the gateway never saw a
    # gpt-multi request). The roster's selectors MUST be present or the
    # composition is single-model in disguise (D39).
    variant_selectors = {variant.client_selector for variant in resolved.variants}
    settings["availableModels"] = sorted(
        {resolved.lead.client_selector, *variant_selectors}
    )
    # Claude's /model picker always retains a "Default" entry; pin the
    # settings default to the same lead so that entry cannot escape the fence.
    settings["model"] = resolved.lead.client_selector
    # Managed sessions own their compaction policy: the compiled capacity and
    # reactive percentage are meaningless if a user-level setting disables
    # auto-compaction underneath them (a disabled auto-compact wedges large
    # managed sessions at the hard context wall).
    settings["autoCompactEnabled"] = True
    if managed_id is not None or hook_command is not None:
        if managed_id is None or hook_command is None:
            raise ScopeError("managed_id and hook_command must be supplied together")
        settings.update(
            _lifecycle_settings(
                managed_id,
                hook_command,
                launch_epoch,
                gateway_base_url=catalog_meta.gateway_base_url,
                token_helper_command=token_helper_command,
                retry_watchdog=True,
            )
        )
    if any(variant.isolation == "worktree" for variant in resolved.variants):
        settings["worktree"] = {"baseRef": "head"}
    unknown = sorted(set(settings) - COMPILED_SETTINGS_KEYS)
    if unknown:
        raise ScopeError(
            f"compiled settings carry keys outside the closed allowlist: {unknown}"
        )
    missing = [key for key in _BASE_WORKFLOW_KEYS if key not in settings]
    if missing:
        raise ScopeError(
            f"package base settings do not supply required workflow keys {missing}"
        )
    return ScopePlan(agent_files=agent_files, settings=settings)


def compile_ordinary_scope(
    *,
    managed_id: str,
    hook_command: str,
    available_models: Iterable[str],
    default_model: str | None = None,
    launch_epoch: int = 0,
    gateway_base_url: str | None = None,
    token_helper_command: str | None = None,
) -> ScopePlan:
    """Minimal tracked gateway scope: hooks and a context-safe model fence."""

    models = sorted(set(available_models))
    if not models:
        raise ScopeError("ordinary gateway scope has no available models")
    selected_default = default_model or models[0]
    if selected_default not in models:
        raise ScopeError("ordinary default model is outside its context profile")
    settings: dict[str, Any] = {
        "availableModels": models,
        "model": selected_default,
        **_lifecycle_settings(
            managed_id,
            hook_command,
            launch_epoch,
            gateway_base_url=gateway_base_url,
            token_helper_command=token_helper_command,
        ),
    }
    unknown = sorted(set(settings) - COMPILED_SETTINGS_KEYS)
    if unknown:
        raise ScopeError(
            f"ordinary settings carry keys outside the closed allowlist: {unknown}"
        )
    return ScopePlan(agent_files={}, settings=settings)


def plan_hash(plan: ScopePlan) -> str:
    """Content hash of a plan: canonical settings plus per-file digests."""

    manifest = {
        "agent_files": {
            relpath: "sha256:" + strict_json.sha256_hex(data)
            for relpath, data in sorted(plan.agent_files.items())
        },
        "settings": plan.settings,
    }
    return strict_json.bundle_digest(manifest)


def scope_dir(state_root: Path | str, session_id: str) -> Path:
    """The live scope directory for a session."""

    return Path(state_root) / "scopes" / _check_session_id(session_id)


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _remove_tree(path: Path) -> None:
    """Remove a scope tree; refuse symlinks and non-directories."""

    info = os.lstat(path)
    if stat.S_ISLNK(info.st_mode):
        raise state.StateError(errno.ELOOP, f"scope path {path} is a symlink")
    if not stat.S_ISDIR(info.st_mode):
        raise state.StateError(
            errno.ENOTDIR, f"scope path {path} is not a directory"
        )
    shutil.rmtree(path)


def _check_relpath(relpath: str) -> PurePosixPath:
    candidate = PurePosixPath(relpath)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise ScopeError(f"unsafe scope-relative path {relpath!r}")
    return candidate


def write_scope(state_root: Path | str, session_id: str, plan: ScopePlan) -> Path:
    """Stage the plan into ``scopes/.<uuid>.new/`` and rename it into place.

    Per-file writes use ``state.atomic_write`` (mode 0600); directories are
    mode 0700 via ``state.ensure_private_dir``. A stale staging directory from
    an interrupted write is removed first. If a live scope already exists it
    is removed just before the rename; the record remains the authority and
    the scope is re-derivable from record+catalog across that window. The
    ``scopes/`` parent is fsynced after the rename.
    """

    _check_session_id(session_id)
    scopes_root = state.ensure_private_dir(Path(state_root) / "scopes")
    staging = scopes_root / f".{session_id}.new"
    live = scopes_root / session_id
    if os.path.lexists(staging):
        _remove_tree(staging)
    state.ensure_private_dir(staging)
    for relpath, data in sorted(plan.agent_files.items()):
        relative = _check_relpath(relpath)
        target = staging.joinpath(*relative.parts)
        state.ensure_private_dir(target.parent)
        state.atomic_write(target, data)
    state.atomic_write(
        staging / "settings.json", strict_json.canonical_file_bytes(plan.settings)
    )
    if os.path.lexists(live):
        _remove_tree(live)
    os.rename(staging, live)
    _fsync_directory(scopes_root)
    return live


def remove_scope(state_root: Path | str, session_id: str) -> bool:
    """Remove a session's live scope and any stale staging dir. Idempotent."""

    _check_session_id(session_id)
    # Validate the scopes PARENT before any destructive work beneath it: a
    # symlinked ancestor must fail closed here, never be followed (final
    # audit L3).
    scopes_root = state.ensure_private_dir(Path(state_root) / "scopes")
    removed = False
    for candidate in (
        scopes_root / session_id,
        scopes_root / f".{session_id}.new",
        scopes_root / f".{session_id}.prev",
    ):
        if os.path.lexists(candidate):
            _remove_tree(candidate)
            removed = True
    if removed:
        _fsync_directory(scopes_root)
    return removed


def _frontmatter_name(path: Path) -> str | None:
    """Line-wise frontmatter ``name:`` extraction (no YAML dependency).

    Returns None for files without a frontmatter block or without a name;
    unreadable files are skipped by the caller (they cannot shadow a loaded
    definition for the same user). YAML inline comments are ignored unless
    they occur inside a quoted scalar.
    """

    try:
        with open(path, "rb") as handle:
            raw = handle.read(65536)
    except OSError:
        return None
    text = raw.decode("utf-8", errors="replace")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    name: str | None = None
    for line in lines[1:]:
        stripped = line.strip()
        if stripped == "---":
            return name
        if stripped.startswith("name:") or stripped.startswith("name :"):
            value = stripped.split(":", 1)[1].strip()
            quote: str | None = None
            escaped = False
            for index, character in enumerate(value):
                if quote == '"':
                    if escaped:
                        escaped = False
                    elif character == "\\":
                        escaped = True
                    elif character == quote:
                        quote = None
                elif quote == "'":
                    if character == quote:
                        quote = None
                elif character in "\"'":
                    quote = character
                elif character == "#" and (
                    index == 0 or value[index - 1].isspace()
                ):
                    value = value[:index].rstrip()
                    break
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1]
            name = value
    return None


def _scan_agents_dir(
    directory: Path, generated_names: frozenset[str]
) -> list[tuple[Path, str]]:
    """Recursively scan one native agent directory, skipping unreadable paths."""

    collisions: list[tuple[Path, str]] = []
    for root, directories, filenames in os.walk(
        directory, topdown=True, onerror=lambda _error: None, followlinks=False
    ):
        directories.sort()
        for filename in sorted(filenames):
            entry = Path(root) / filename
            try:
                if not entry.is_file() or entry.suffix != ".md":
                    continue
            except OSError:
                continue
            name = _frontmatter_name(entry)
            if name is not None and name in generated_names:
                collisions.append((entry, name))
    return collisions


def find_cm_collisions(
    cwd: Path | str,
    add_dirs: Iterable[Path | str],
    generated_names: frozenset[str] | set[str],
    *,
    managed_agents_dir: Path | None = DEFAULT_MANAGED_AGENTS_DIR,
) -> list[tuple[Path, str]]:
    """Exact ``cm-*`` name collisions outside the managed scope (fail closed).

    Scans (a) every ``.claude/agents/`` directory from ``cwd`` up to and
    including the git root (first ancestor containing ``.git``) or the
    filesystem root, (b) ``.claude/agents/`` under each passthrough
    ``--add-dir``, and (c) the managed settings agents directory when it
    exists and is readable. ``add_dirs`` must be the user passthrough dirs
    only — never the session's own scope dir. Returns a deterministic sorted
    list of ``(offending file, colliding name)``; empty means clean. Exposed
    for Doctor's collision check as well as the durable launch gate.
    """

    names = frozenset(generated_names)
    collisions: list[tuple[Path, str]] = []
    seen: set[Path] = set()

    def scan(directory: Path) -> None:
        try:
            key = directory.resolve()
        except OSError:
            key = directory
        if key in seen:
            return
        seen.add(key)
        collisions.extend(_scan_agents_dir(directory, names))

    start = Path(cwd).resolve()
    for ancestor in (start, *start.parents):
        candidate = ancestor / ".claude" / "agents"
        if candidate.is_dir():
            scan(candidate)
        if (ancestor / ".git").exists():
            break
    for add_dir in add_dirs:
        candidate = Path(add_dir) / ".claude" / "agents"
        if candidate.is_dir():
            scan(candidate)
    if managed_agents_dir is not None and managed_agents_dir.is_dir():
        scan(managed_agents_dir)
    return sorted(collisions, key=lambda item: (str(item[0]), item[1]))
